### ISSUE TITLE
great job

### ISSUE THREAD

**Issue by crypt0miester** [jacekv/Solana-Intro#1]
why not use anchorpy? you would run into problems when you call huge functions with a lotta data. i.e. adding config lines in the candy machine.

**Comment by jacekv** [comment]
I prefer to explore the underlying mechanics before I use a framework :)
This helps me to understand how stuff works and in case there is an error in the framework, I am able to quicker identify it.

Makes sense?

**Comment by crypt0miester** [comment]
makes sense. still inefficient though, imo. good luck.

**Comment by jacekv** [comment]
Sure, but as said, it is not about being efficient in the beginning.

My impression on anchor.py is that it looks incomplete, but I hadn't yet the chance to do a deep dive :) One step at a time ;)
